### ISSUE TITLE
gantt intl util breaks when formatting message

### ISSUE THREAD

**Issue by ali-sadeghin** [IBM/gantt-chart#11]
formatString(tpl, obj) {
    // tpl = this.getString(tpl, tpl);
    // return tpl.replace(/\{(\w+)\}/g, (_, key) => obj[key]);
    return this.getIntl().formatMessage({ id: key, defaultMessage: defaultValue }, obj);
  },

This code breaks when entering erroneous things in the DO4WS Dashboard's gantt editor (like a bad column name...). The error stack is:

Uncaught (in promise) ReferenceError: key is not defined
    at Object.formatString (utils.js:320)
    at ErrorHandler.convertError (index.js:207)
    at ErrorHandler.addError (index.js:106)
    at GanttPanel.setConfiguration (ganttpanel.js:245)
    at ganttpanel.js:53

**Comment by ali-sadeghin** [comment]
looks like this code:

  formatString(tpl, obj) {
    // tpl = this.getString(tpl, tpl);
    // return tpl.replace(/\{(\w+)\}/g, (_, key) => obj[key]);
    return this.getIntl().formatMessage({ id: key, defaultMessage: defaultValue }, obj);
  },

is missing key and defaultValue?

Shoudln't it rather be:

  formatString: function formatString(tpl, obj) {
    // tpl = this.getString(tpl, tpl);
    // return tpl.replace(/\{(\w+)\}/g, (_, key) => obj[key]);
    return this.getIntl().formatMessage({ id: tpl, defaultMessage: obj}, obj);

since in the call, the values are:
tpl: "gantt.error.title.fmt"
formatString:
  msg: "Error initializing the Gantt"
  title: "Could not configure data for resources. Probably a configuration issue with key(s) quantity"
  },

tpl looks definitely like a key here...

**Comment by delhoume** [comment]
v0.5.8 fixes the issue
