### ISSUE TITLE
Where is the ibm-gantt-chart.js file?

### ISSUE THREAD

**Issue by angelieri** [IBM/gantt-chart#12]
Sorry about the question but I'm not able to find it.

Thansk!

**Comment by gillesdandrea** [comment]
Hello,
the distribution files are not committed in github.
You should `npm install ibm-gantt-chart` to get the `ibm-gantt-chart.js` file.

Or you can transpile the GitHub version with:
```
yarn install
yarn build
```
and then look into `packages/ibm-gantt-chart/dist`
