### ISSUE TITLE
Cross-Site Scripting (XSS) in ibm-gantt-chart

### ISSUE THREAD

**Issue by ready-research** [IBM/gantt-chart#22]
# Description

`ibm-gantt-chart` is vulnerable to `Cross-Site Scripting (XSS)`.

# Steps To Reproduce

1. Open https://www.npmjs.com/package/ibm-gantt-chart
2. Copy the code from the usage example and make a test.html  https://www.npmjs.com/package/ibm-gantt-chart#usage
3. And use `<link href="https://unpkg.com/ibm-gantt-chart@0.5.9/dist/ibm-gantt-chart.css" rel="stylesheet" />` and
   `<script src="https://unpkg.com/ibm-gantt-chart@0.5.9/dist/ibm-gantt-chart.js"></script>`
4. Insert the xss payload in name field in data Ex: `name: 'Bethanie"<img src=x onerror=alert(1)>',`
5. Open the test.html file in any browser, XSS payload will get executed.
![ibm-gantt-chart](https://user-images.githubusercontent.com/72916209/105848382-e4d17500-6004-11eb-94c8-8a00068f6187.PNG)

**Comment by ready-research** [comment]
@delhoume @gillesdandrea ^^^^

**Comment by ready-research** [comment]
@delhoume @ali-sadeghin  Please validate this issue?

**Comment by Jan-Kruse** [comment]
@gillesdandrea @delhoume Is any action planned for this?

**Comment by delhoume** [comment]
Yes, a fix has been found by a contributor, but he has not submitted yet a pull request. So I am not sure how we can use it.

https://github.com/418sec/gantt-chart/pull/1/commits/6ae2acccadee261ca038c85e8d24287a1b1147ff

**Comment by ready-research** [comment]
@delhoume Please comment `@huntr-helper - LGTM` in https://github.com/418sec/gantt-chart/pull/1

It will open a PR automatically.

**Comment by delhoume** [comment]
@huntr-helper - LGTM in 418sec#1

**Comment by JamieSlome** [comment]
@delhoume - this technology is no longer supported.

I will manually open the PR for you!

**Comment by JamieSlome** [comment]
@delhoume - sorted! 🎉 

https://github.com/IBM/gantt-chart/pull/33
