### ISSUE TITLE
How to generate vanilla bundles (no jQuery or React)?

### ISSUE THREAD

**Issue by Stp3103** [IBM/gantt-chart#34]
I am trying to use IBM-gantt-chart in Anvil (see Anvil.works). I have successfully generated bundle files by running 'npm run build'. I can see that jQuery has been included in the js file. My issue is that the Anvil platform documentation states -'it is a bad idea to load jQuery or Bootstrap Javascript explicitly from an HTML template — it will overwrite the versions Anvil has already loaded.'. The IBM-Gantt documentation suggests that it should be possible to produce a 'vanilla' bundle file which does not include jQuery but I can't find any documentation on how to do this, nor can I work out how to do it from looking at the code (I am new to JavaScript). Any pointers would be gratefully received. Thanks

**Comment by delhoume** [comment]
You have a development page at https://github.com/IBM/gantt-chart/blob/master/CONTRIBUTING.md

You have to follow the instructions using yarn an lerna (in "How to publish", up to step 2) , and files for vanilla bundles will be created in packages/ibm-gantt-chart/dist

**Comment by delhoume** [comment]
You will find example of usage in

https://github.com/IBM/gantt-chart/blob/master/packages/ibm-gantt-chart/public/examples/basic-standalone/index.html

**Comment by Stp3103** [comment]
Dear Frederic,

Thank you for your prompt response. I will let you know how it goes.

Regards
Steve

**Comment by Stp3103** [comment]
'yarn install' step seems to have worked ok. Step ended with following messages: -
[4/4] Building fresh packages...
success Saved lockfile.
Done in 1446.17s.

'lerna link' step finished very quickly with the following messages (no warnings or errors): -
lerna notice cli v4.0.0
lerna info Symlinking packages and binaries

No new packages appeared in my /dist/ folder. Any thoughts?

**Comment by Stp3103** [comment]
Apologies I have realised I have followed the 'How to develop' instructions and not the 'How to publish instructions'!! Senior moment. I will follow the CORRECT instructions and revert.

**Comment by Stp3103** [comment]
I successfully produced the vanilla bundles using the instructions in 'How to publish' section. Thank you.
