### ISSUE TITLE
How to translate timeline date into japanese ?

### ISSUE THREAD

**Issue by ZenTal29** [IBM/gantt-chart#52]
Can someone give me an example to change timeline language to japanese ?

I found this setTimeWindow function at  **ibm-gantt-chart/jquery/timeline.js**  that can do this but I haven't figured out how to configure it. Please help me !!

**Comment by delhoume** [comment]
You may look at https://github.com/IBM/gantt-chart/issues/21 for some info.

**Comment by ZenTal29** [comment]
I've read it before, but it's not very clear. Can you help me explain a little more clearly. Or it would be nice if there are basic steps.

**Comment by delhoume** [comment]
It seems that it should be
gantt.utils.setIntl({ locale : 'ja'} );

no ?

**Comment by ZenTal29** [comment]
I tried this code and it works. Thanks for your advice !

 gantt.utils.setIntl({locale : 'ja', formatMessage: () => {id: 'ja'}})

**Comment by delhoume** [comment]
You're welcome !
