### ISSUE TITLE
Question: Show tooltip on click

### ISSUE THREAD

**Issue by spliner21** [IBM/gantt-chart#56]
Hi,

I need to change the behavior of the gantt chart, so that tooltip would show up on click. Is it possible to achieve somehow? Or will I have to alter the code of the plugin?

Thanks in advance!

**Comment by delcacho** [comment]
Place this in a click listener:

activityClicked(e, act, date, row) {
        act.gantt.tooltip._tooltip.style.visibility = "visible"
      },

**Comment by yobdoy** [comment]
> Place this in a click listener:
> 
> activityClicked(e, act, date, row) { act.gantt.tooltip._tooltip.style.visibility = "visible" },

@delcacho hi Thanks for the example, this is what I've tried and it's working with showing me the HTML element object, however this alert is shown everywhere I click and it doesn't get the activity clicked function,  would it be possible to provide an example,

Also i checked the code [here](https://github.com/IBM/gantt-chart/blob/fdfed59decd3da1b36b3f54257f927398e2c8682/packages/ibm-gantt-chart/src/timetable/timetable.js#L899) but not sure to which element the click event needs to be bound to,

Thanks!

`gantt.timeTable.utils.addEventListener(this,'click',(e)=>{
  e.preventDefault;
  alert(e.target)
},true)`
